language: python
sudo: false
dist: bionic

python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "pypy"
    - "pypy3"

env:
    - RUN=nosetests
    - RUN=build_sphinx

matrix:
    allow_failures:
        - python: "pypy"
        - python: "pypy3"

install:
    - ./.travis.install.sh

script:
    - ./.travis.script.sh
